name: 'dbt_example'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_example'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_example:
    # Config indicated by + and applies to all files under models/example/
    # example:
    staging:
      schema: staging
      materialized: table
      tags: [staging]
    
    intermediate: # aqui não vamos criar tabelas mais vamos executar o codigo
      materialized: ephemeral
      tags: [intermediate]
    
    marts:
      schema: marts
      materialized: table
      tags: [marts]

seeds: # aqui vamos colocar fora do schema dbt_dw
  dbt_example:
    +schema: seeds
    tags: ['seeds']
    
  # snapshots:
  #   dbt_example:
  #     tags: ['snapshots']
  #     schema: snapshots